refactor(git): 优化pre-commit脚本

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -40,22 +40,22 @@ fi
 # 输出信息
 if [ $pmd_needed -eq 1 ]; then
     echo "🦉 Running PMD on changed Java files..."
-    ./gradlew pmdMain --parallel --build-cache
-    if [ $? -ne 0 ]; then
-        echo "🌥️ PMD check failed. Please fix the issues before committing."
-        exit 1
+    if ./gradlew pmdMain --parallel --build-cache; then
+      echo "🎉 PMD checks passed.";
+    else
+      echo "🌥️ PMD check failed. Please fix the issues before committing.";
+      exit 1
     fi
-    echo "🎉 PMD checks passed."
 fi
 
 if [ $checkstyle_needed -eq 1 ]; then
     echo "🦉 Running Checkstyle on changed Java, Properties, and XML files..."
-    ./gradlew checkstyleMain --parallel --build-cache
-    if [ $? -ne 0 ]; then
-        echo "🌥️ Checkstyle check failed. Please fix the issues before committing."
-        exit 1
+    if ./gradlew checkstyleMain --parallel --build-cache; then
+      echo "🎉 Checkstyle checks passed.";
+    else
+      echo "🌥️ Checkstyle check failed. Please fix the issues before committing.";
+      exit 1
     fi
-    echo "🎉 Checkstyle checks passed."
 fi
 
 if [ $update_license_needed -eq 1 ]; then
